server:
  port: 8080
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: W@2915djkq#
    username: root
  jpa:
    hibernate:
      ddl-auto: update
