server:
  port: 8083
spring:
  application:
    name: basket
  datasource:
    url: jdbc:mysql://localhost:3306/basket
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: W@2915djkq#
    username: root
  jpa:
    hibernate:
      ddl-auto: update
