server:
  port: 8081
spring:
  application:
    name: stock
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: W@2915djkq#
    username: root
  jpa:
    hibernate:
      ddl-auto: update
